// flow-typed signature: 04195685e75a97ea78f9e223e509c2c4
// flow-typed version: <<STUB>>/await-exec_v0.1.2/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'await-exec'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'await-exec' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'await-exec/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'await-exec/index' {
  declare module.exports: $Exports<'await-exec'>;
}
declare module 'await-exec/index.js' {
  declare module.exports: $Exports<'await-exec'>;
}
declare module 'await-exec/test.js' {
  declare module.exports: $Exports<'await-exec/test'>;
}
