// flow-typed signature: 1f2705e290dfa35131eb2cd3e1eff51e
// flow-typed version: <<STUB>>/aws-sam-webpack-plugin_v0.6.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-sam-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-sam-webpack-plugin' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-sam-webpack-plugin/dist' {
    declare module.exports: any;
}

// Filename aliases
declare module 'aws-sam-webpack-plugin/dist/index' {
    declare module.exports: $Exports<'aws-sam-webpack-plugin/dist'>;
}
declare module 'aws-sam-webpack-plugin/dist/index.js' {
    declare module.exports: $Exports<'aws-sam-webpack-plugin/dist'>;
}
