// flow-typed signature: 0edf1826a6f9ae4fe445678eae9bf5a5
// flow-typed version: <<STUB>>/combine-reducers-global-state_v1.0.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'combine-reducers-global-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'combine-reducers-global-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'combine-reducers-global-state/es' {
  declare module.exports: any;
}

declare module 'combine-reducers-global-state/lib' {
  declare module.exports: any;
}

declare module 'combine-reducers-global-state/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'combine-reducers-global-state/es/index' {
  declare module.exports: $Exports<'combine-reducers-global-state/es'>;
}
declare module 'combine-reducers-global-state/es/index.js' {
  declare module.exports: $Exports<'combine-reducers-global-state/es'>;
}
declare module 'combine-reducers-global-state/lib/index' {
  declare module.exports: $Exports<'combine-reducers-global-state/lib'>;
}
declare module 'combine-reducers-global-state/lib/index.js' {
  declare module.exports: $Exports<'combine-reducers-global-state/lib'>;
}
declare module 'combine-reducers-global-state/src/index' {
  declare module.exports: $Exports<'combine-reducers-global-state/src'>;
}
declare module 'combine-reducers-global-state/src/index.js' {
  declare module.exports: $Exports<'combine-reducers-global-state/src'>;
}
