// flow-typed signature: 4753fe1db203edf8f2a3834aa34f69b8
// flow-typed version: <<STUB>>/crypto-random-string_v3.2.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crypto-random-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crypto-random-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'crypto-random-string/index' {
  declare module.exports: $Exports<'crypto-random-string'>;
}
declare module 'crypto-random-string/index.js' {
  declare module.exports: $Exports<'crypto-random-string'>;
}
