// flow-typed signature: 8835eb53caed79812ac4e3b36e1dccb3
// flow-typed version: <<STUB>>/dpdm_v3.4.3/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dpdm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dpdm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dpdm/lib/bin/dpdm' {
  declare module.exports: any;
}

declare module 'dpdm/lib/consts' {
  declare module.exports: any;
}

declare module 'dpdm/lib' {
  declare module.exports: any;
}

declare module 'dpdm/lib/parser' {
  declare module.exports: any;
}

declare module 'dpdm/lib/types' {
  declare module.exports: any;
}

declare module 'dpdm/lib/utils' {
  declare module.exports: any;
}

declare module 'dpdm/lib/utils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dpdm/lib/bin/dpdm.js' {
  declare module.exports: $Exports<'dpdm/lib/bin/dpdm'>;
}
declare module 'dpdm/lib/consts.js' {
  declare module.exports: $Exports<'dpdm/lib/consts'>;
}
declare module 'dpdm/lib/index' {
  declare module.exports: $Exports<'dpdm/lib'>;
}
declare module 'dpdm/lib/index.js' {
  declare module.exports: $Exports<'dpdm/lib'>;
}
declare module 'dpdm/lib/parser.js' {
  declare module.exports: $Exports<'dpdm/lib/parser'>;
}
declare module 'dpdm/lib/types.js' {
  declare module.exports: $Exports<'dpdm/lib/types'>;
}
declare module 'dpdm/lib/utils.js' {
  declare module.exports: $Exports<'dpdm/lib/utils'>;
}
declare module 'dpdm/lib/utils.spec.js' {
  declare module.exports: $Exports<'dpdm/lib/utils.spec'>;
}
