// flow-typed signature: eb0056ecd26862662893cdff46db1580
// flow-typed version: <<STUB>>/eslint-plugin-autofix_v1.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-autofix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-autofix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-autofix/lib/ast-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/configs/all' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/configs/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/configs/unsafe' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-alert' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-caller' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-console' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-debugger' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-eq-null' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-new-symbol' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-plusplus' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-proto' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-prototype-builtins' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-throw-literal' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-unused-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-useless-catch' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/no-useless-concat' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/prefer-spread' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/radix' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/rules/valid-typeof' {
  declare module.exports: any;
}

declare module 'eslint-plugin-autofix/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-autofix/lib/ast-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/ast-utils'>;
}
declare module 'eslint-plugin-autofix/lib/configs/all.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/configs/all'>;
}
declare module 'eslint-plugin-autofix/lib/configs/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/configs/recommended'>;
}
declare module 'eslint-plugin-autofix/lib/configs/unsafe.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/configs/unsafe'>;
}
declare module 'eslint-plugin-autofix/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib'>;
}
declare module 'eslint-plugin-autofix/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib'>;
}
declare module 'eslint-plugin-autofix/lib/rules.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-alert.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-alert'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-caller.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-caller'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-console.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-console'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-debugger.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-debugger'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-eq-null.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-eq-null'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-new-symbol.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-new-symbol'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-plusplus.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-plusplus'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-proto.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-proto'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-prototype-builtins.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-prototype-builtins'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-throw-literal.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-throw-literal'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-unused-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-unused-vars'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-useless-catch.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-useless-catch'>;
}
declare module 'eslint-plugin-autofix/lib/rules/no-useless-concat.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/no-useless-concat'>;
}
declare module 'eslint-plugin-autofix/lib/rules/prefer-spread.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/prefer-spread'>;
}
declare module 'eslint-plugin-autofix/lib/rules/radix.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/radix'>;
}
declare module 'eslint-plugin-autofix/lib/rules/valid-typeof.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/rules/valid-typeof'>;
}
declare module 'eslint-plugin-autofix/lib/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-autofix/lib/utils'>;
}
