// flow-typed signature: a608c177d325164ab29cba112318be66
// flow-typed version: <<STUB>>/fontmin_v0.9.8/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fontmin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fontmin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fontmin/cli' {
  declare module.exports: any;
}

declare module 'fontmin/lib/mime-types' {
  declare module.exports: any;
}

declare module 'fontmin/lib/util' {
  declare module.exports: any;
}

declare module 'fontmin/plugins/css' {
  declare module.exports: any;
}

declare module 'fontmin/plugins/glyph' {
  declare module.exports: any;
}

declare module 'fontmin/plugins/otf2ttf' {
  declare module.exports: any;
}

declare module 'fontmin/plugins/svg2ttf' {
  declare module.exports: any;
}

declare module 'fontmin/plugins/svgs2ttf' {
  declare module.exports: any;
}

declare module 'fontmin/plugins/ttf2eot' {
  declare module.exports: any;
}

declare module 'fontmin/plugins/ttf2svg' {
  declare module.exports: any;
}

declare module 'fontmin/plugins/ttf2woff' {
  declare module.exports: any;
}

declare module 'fontmin/plugins/ttf2woff2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fontmin/cli.js' {
  declare module.exports: $Exports<'fontmin/cli'>;
}
declare module 'fontmin/index' {
  declare module.exports: $Exports<'fontmin'>;
}
declare module 'fontmin/index.js' {
  declare module.exports: $Exports<'fontmin'>;
}
declare module 'fontmin/lib/mime-types.js' {
  declare module.exports: $Exports<'fontmin/lib/mime-types'>;
}
declare module 'fontmin/lib/util.js' {
  declare module.exports: $Exports<'fontmin/lib/util'>;
}
declare module 'fontmin/plugins/css.js' {
  declare module.exports: $Exports<'fontmin/plugins/css'>;
}
declare module 'fontmin/plugins/glyph.js' {
  declare module.exports: $Exports<'fontmin/plugins/glyph'>;
}
declare module 'fontmin/plugins/otf2ttf.js' {
  declare module.exports: $Exports<'fontmin/plugins/otf2ttf'>;
}
declare module 'fontmin/plugins/svg2ttf.js' {
  declare module.exports: $Exports<'fontmin/plugins/svg2ttf'>;
}
declare module 'fontmin/plugins/svgs2ttf.js' {
  declare module.exports: $Exports<'fontmin/plugins/svgs2ttf'>;
}
declare module 'fontmin/plugins/ttf2eot.js' {
  declare module.exports: $Exports<'fontmin/plugins/ttf2eot'>;
}
declare module 'fontmin/plugins/ttf2svg.js' {
  declare module.exports: $Exports<'fontmin/plugins/ttf2svg'>;
}
declare module 'fontmin/plugins/ttf2woff.js' {
  declare module.exports: $Exports<'fontmin/plugins/ttf2woff'>;
}
declare module 'fontmin/plugins/ttf2woff2.js' {
  declare module.exports: $Exports<'fontmin/plugins/ttf2woff2'>;
}
