// flow-typed signature: c0168db2e6b79c176825b896b0908b08
// flow-typed version: <<STUB>>/git-revision-webpack-plugin_v3.0.6/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-revision-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-revision-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-revision-webpack-plugin/lib/build-file' {
  declare module.exports: any;
}

declare module 'git-revision-webpack-plugin/lib/helpers/remove-empty-lines' {
  declare module.exports: any;
}

declare module 'git-revision-webpack-plugin/lib/helpers/run-git-command' {
  declare module.exports: any;
}

declare module 'git-revision-webpack-plugin/lib/index.integration.spec' {
  declare module.exports: any;
}

declare module 'git-revision-webpack-plugin/lib' {
  declare module.exports: any;
}

declare module 'git-revision-webpack-plugin/lib/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-revision-webpack-plugin/lib/build-file.js' {
  declare module.exports: $Exports<'git-revision-webpack-plugin/lib/build-file'>;
}
declare module 'git-revision-webpack-plugin/lib/helpers/remove-empty-lines.js' {
  declare module.exports: $Exports<'git-revision-webpack-plugin/lib/helpers/remove-empty-lines'>;
}
declare module 'git-revision-webpack-plugin/lib/helpers/run-git-command.js' {
  declare module.exports: $Exports<'git-revision-webpack-plugin/lib/helpers/run-git-command'>;
}
declare module 'git-revision-webpack-plugin/lib/index.integration.spec.js' {
  declare module.exports: $Exports<'git-revision-webpack-plugin/lib/index.integration.spec'>;
}
declare module 'git-revision-webpack-plugin/lib/index' {
  declare module.exports: $Exports<'git-revision-webpack-plugin/lib'>;
}
declare module 'git-revision-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'git-revision-webpack-plugin/lib'>;
}
declare module 'git-revision-webpack-plugin/lib/index.spec.js' {
  declare module.exports: $Exports<'git-revision-webpack-plugin/lib/index.spec'>;
}
