// flow-typed signature: 3727b91bedff17180fe7880342ad5916
// flow-typed version: <<STUB>>/json-stringify-deterministic_v1.0.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-stringify-deterministic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-stringify-deterministic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-stringify-deterministic/lib/defaults' {
  declare module.exports: any;
}

declare module 'json-stringify-deterministic/lib' {
  declare module.exports: any;
}

declare module 'json-stringify-deterministic/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-stringify-deterministic/lib/defaults.js' {
  declare module.exports: $Exports<'json-stringify-deterministic/lib/defaults'>;
}
declare module 'json-stringify-deterministic/lib/index' {
  declare module.exports: $Exports<'json-stringify-deterministic/lib'>;
}
declare module 'json-stringify-deterministic/lib/index.js' {
  declare module.exports: $Exports<'json-stringify-deterministic/lib'>;
}
declare module 'json-stringify-deterministic/lib/util.js' {
  declare module.exports: $Exports<'json-stringify-deterministic/lib/util'>;
}
