// flow-typed signature: 1bfa7ce17e4c80412d8922d5c32a9117
// flow-typed version: <<STUB>>/jwk-to-pem_v2.0.3/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jwk-to-pem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jwk-to-pem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jwk-to-pem/src/asn1/algorithm-identifier' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/asn1/private-key-info' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/asn1/public-key-info' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/asn1/version' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/b64-to-bn' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/ec' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/jwk-to-pem' {
  declare module.exports: any;
}

declare module 'jwk-to-pem/src/rsa' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jwk-to-pem/src/asn1/algorithm-identifier.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/asn1/algorithm-identifier'>;
}
declare module 'jwk-to-pem/src/asn1/private-key-info.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/asn1/private-key-info'>;
}
declare module 'jwk-to-pem/src/asn1/public-key-info.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/asn1/public-key-info'>;
}
declare module 'jwk-to-pem/src/asn1/version.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/asn1/version'>;
}
declare module 'jwk-to-pem/src/b64-to-bn.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/b64-to-bn'>;
}
declare module 'jwk-to-pem/src/ec.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/ec'>;
}
declare module 'jwk-to-pem/src/jwk-to-pem.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/jwk-to-pem'>;
}
declare module 'jwk-to-pem/src/rsa.js' {
  declare module.exports: $Exports<'jwk-to-pem/src/rsa'>;
}
