// flow-typed signature: a67725228c343f885191a3072314bfab
// flow-typed version: <<STUB>>/parse-url_v5.0.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-url/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-url/lib/index' {
  declare module.exports: $Exports<'parse-url/lib'>;
}
declare module 'parse-url/lib/index.js' {
  declare module.exports: $Exports<'parse-url/lib'>;
}
