// flow-typed signature: acf198c5d731b5908cdd101a81dc2263
// flow-typed version: <<STUB>>/pino-pretty_v4.0.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pino-pretty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pino-pretty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pino-pretty/bin' {
  declare module.exports: any;
}

declare module 'pino-pretty/lib/colors' {
  declare module.exports: any;
}

declare module 'pino-pretty/lib/constants' {
  declare module.exports: any;
}

declare module 'pino-pretty/lib/utils' {
  declare module.exports: any;
}

declare module 'pino-pretty/test/basic.test' {
  declare module.exports: any;
}

declare module 'pino-pretty/test/cli-rc.test' {
  declare module.exports: any;
}

declare module 'pino-pretty/test/cli.test' {
  declare module.exports: any;
}

declare module 'pino-pretty/test/crlf.test' {
  declare module.exports: any;
}

declare module 'pino-pretty/test/error-objects.test' {
  declare module.exports: any;
}

declare module 'pino-pretty/test/lib/colors.test' {
  declare module.exports: any;
}

declare module 'pino-pretty/test/lib/utils.internals.test' {
  declare module.exports: any;
}

declare module 'pino-pretty/test/lib/utils.public.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pino-pretty/bin.js' {
  declare module.exports: $Exports<'pino-pretty/bin'>;
}
declare module 'pino-pretty/index' {
  declare module.exports: $Exports<'pino-pretty'>;
}
declare module 'pino-pretty/index.js' {
  declare module.exports: $Exports<'pino-pretty'>;
}
declare module 'pino-pretty/lib/colors.js' {
  declare module.exports: $Exports<'pino-pretty/lib/colors'>;
}
declare module 'pino-pretty/lib/constants.js' {
  declare module.exports: $Exports<'pino-pretty/lib/constants'>;
}
declare module 'pino-pretty/lib/utils.js' {
  declare module.exports: $Exports<'pino-pretty/lib/utils'>;
}
declare module 'pino-pretty/test/basic.test.js' {
  declare module.exports: $Exports<'pino-pretty/test/basic.test'>;
}
declare module 'pino-pretty/test/cli-rc.test.js' {
  declare module.exports: $Exports<'pino-pretty/test/cli-rc.test'>;
}
declare module 'pino-pretty/test/cli.test.js' {
  declare module.exports: $Exports<'pino-pretty/test/cli.test'>;
}
declare module 'pino-pretty/test/crlf.test.js' {
  declare module.exports: $Exports<'pino-pretty/test/crlf.test'>;
}
declare module 'pino-pretty/test/error-objects.test.js' {
  declare module.exports: $Exports<'pino-pretty/test/error-objects.test'>;
}
declare module 'pino-pretty/test/lib/colors.test.js' {
  declare module.exports: $Exports<'pino-pretty/test/lib/colors.test'>;
}
declare module 'pino-pretty/test/lib/utils.internals.test.js' {
  declare module.exports: $Exports<'pino-pretty/test/lib/utils.internals.test'>;
}
declare module 'pino-pretty/test/lib/utils.public.test.js' {
  declare module.exports: $Exports<'pino-pretty/test/lib/utils.public.test'>;
}
