// flow-typed signature: 5ee6d42a1aa667a18532215870ca99a4
// flow-typed version: <<STUB>>/reduce-reducers_v1.0.4/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reduce-reducers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reduce-reducers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reduce-reducers/es' {
  declare module.exports: any;
}

declare module 'reduce-reducers/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reduce-reducers/es/index' {
  declare module.exports: $Exports<'reduce-reducers/es'>;
}
declare module 'reduce-reducers/es/index.js' {
  declare module.exports: $Exports<'reduce-reducers/es'>;
}
declare module 'reduce-reducers/lib/index' {
  declare module.exports: $Exports<'reduce-reducers/lib'>;
}
declare module 'reduce-reducers/lib/index.js' {
  declare module.exports: $Exports<'reduce-reducers/lib'>;
}
