// flow-typed signature: 075baef0eb9587e9c7cf6d1e9e69bbfd
// flow-typed version: <<STUB>>/roman-decimal_v1.0.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'roman-decimal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'roman-decimal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'roman-decimal/roman' {
  declare module.exports: any;
}

// Filename aliases
declare module 'roman-decimal/roman.js' {
  declare module.exports: $Exports<'roman-decimal/roman'>;
}
