// flow-typed signature: 819c1989d037c40b7e5f9e04c444a7b8
// flow-typed version: <<STUB>>/tailwindcss-filters_v3.0.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwindcss-filters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwindcss-filters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tailwindcss-filters/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tailwindcss-filters/index' {
  declare module.exports: $Exports<'tailwindcss-filters'>;
}
declare module 'tailwindcss-filters/index.js' {
  declare module.exports: $Exports<'tailwindcss-filters'>;
}
declare module 'tailwindcss-filters/test.js' {
  declare module.exports: $Exports<'tailwindcss-filters/test'>;
}
