// flow-typed signature: 88047acfdb71ef79d6b6f79456872e49
// flow-typed version: <<STUB>>/tailwindcss-bg-alpha_v2.1.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwindcss-bg-alpha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwindcss-bg-alpha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tailwindcss-bg-alpha/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tailwindcss-bg-alpha/index' {
  declare module.exports: $Exports<'tailwindcss-bg-alpha'>;
}
declare module 'tailwindcss-bg-alpha/index.js' {
  declare module.exports: $Exports<'tailwindcss-bg-alpha'>;
}
declare module 'tailwindcss-bg-alpha/test.js' {
  declare module.exports: $Exports<'tailwindcss-bg-alpha/test'>;
}
