// flow-typed signature: 9204053c9bfbc39c2f1ac1a8d52bdfbf
// flow-typed version: <<STUB>>/tailwindcss-filters_v3.0.0/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwindcss-filters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwindcss-filters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tailwindcss-filters/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tailwindcss-filters/index' {
  declare module.exports: $Exports<'tailwindcss-filters'>;
}
declare module 'tailwindcss-filters/index.js' {
  declare module.exports: $Exports<'tailwindcss-filters'>;
}
declare module 'tailwindcss-filters/test.js' {
  declare module.exports: $Exports<'tailwindcss-filters/test'>;
}
