// flow-typed signature: d57bc5716c89320d96766262c13b2dbc
// flow-typed version: <<STUB>>/testcafe-reporter-html_v1.4.6/flow_v0.122.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testcafe-reporter-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testcafe-reporter-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testcafe-reporter-html/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testcafe-reporter-html/lib/index' {
  declare module.exports: $Exports<'testcafe-reporter-html/lib'>;
}
declare module 'testcafe-reporter-html/lib/index.js' {
  declare module.exports: $Exports<'testcafe-reporter-html/lib'>;
}
