// flow-typed signature: a7d179149eacc9e315c0166179028147
// flow-typed version: <<STUB>>/testcafe-reporter-custom_v1.1.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testcafe-reporter-custom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testcafe-reporter-custom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testcafe-reporter-custom/lib' {
  declare module.exports: any;
}

declare module 'testcafe-reporter-custom/lib/utils/config.utils' {
  declare module.exports: any;
}

declare module 'testcafe-reporter-custom/lib/utils/typescript.utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testcafe-reporter-custom/lib/index' {
  declare module.exports: $Exports<'testcafe-reporter-custom/lib'>;
}
declare module 'testcafe-reporter-custom/lib/index.js' {
  declare module.exports: $Exports<'testcafe-reporter-custom/lib'>;
}
declare module 'testcafe-reporter-custom/lib/utils/config.utils.js' {
  declare module.exports: $Exports<'testcafe-reporter-custom/lib/utils/config.utils'>;
}
declare module 'testcafe-reporter-custom/lib/utils/typescript.utils.js' {
  declare module.exports: $Exports<'testcafe-reporter-custom/lib/utils/typescript.utils'>;
}
