// flow-typed signature: 264a016e563510be50c39434587a425b
// flow-typed version: <<STUB>>/ttf2woff2_v3.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ttf2woff2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ttf2woff2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ttf2woff2/bin/ttf2woff2' {
  declare module.exports: any;
}

declare module 'ttf2woff2/jssrc' {
  declare module.exports: any;
}

declare module 'ttf2woff2/jssrc/post' {
  declare module.exports: any;
}

declare module 'ttf2woff2/jssrc/ttf2woff2' {
  declare module.exports: any;
}

declare module 'ttf2woff2/src' {
  declare module.exports: any;
}

declare module 'ttf2woff2/tests/cli.mocha' {
  declare module.exports: any;
}

declare module 'ttf2woff2/tests/tests.mocha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ttf2woff2/bin/ttf2woff2.js' {
  declare module.exports: $Exports<'ttf2woff2/bin/ttf2woff2'>;
}
declare module 'ttf2woff2/jssrc/index' {
  declare module.exports: $Exports<'ttf2woff2/jssrc'>;
}
declare module 'ttf2woff2/jssrc/index.js' {
  declare module.exports: $Exports<'ttf2woff2/jssrc'>;
}
declare module 'ttf2woff2/jssrc/post.js' {
  declare module.exports: $Exports<'ttf2woff2/jssrc/post'>;
}
declare module 'ttf2woff2/jssrc/ttf2woff2.js' {
  declare module.exports: $Exports<'ttf2woff2/jssrc/ttf2woff2'>;
}
declare module 'ttf2woff2/src/index' {
  declare module.exports: $Exports<'ttf2woff2/src'>;
}
declare module 'ttf2woff2/src/index.js' {
  declare module.exports: $Exports<'ttf2woff2/src'>;
}
declare module 'ttf2woff2/tests/cli.mocha.js' {
  declare module.exports: $Exports<'ttf2woff2/tests/cli.mocha'>;
}
declare module 'ttf2woff2/tests/tests.mocha.js' {
  declare module.exports: $Exports<'ttf2woff2/tests/tests.mocha'>;
}
