// flow-typed signature: 78f4a306b5282f137e270f144b5f4b3f
// flow-typed version: <<STUB>>/tumult_v3.0.14/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tumult'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tumult' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tumult/dist/tumult.min' {
    declare module.exports: any;
}

declare module 'tumult/lib' {
    declare module.exports: any;
}

declare module 'tumult/lib/perlin/perlin1' {
    declare module.exports: any;
}

declare module 'tumult/lib/perlin/perlin2' {
    declare module.exports: any;
}

declare module 'tumult/lib/perlin/perlin3' {
    declare module.exports: any;
}

declare module 'tumult/lib/perlin/perlin4' {
    declare module.exports: any;
}

declare module 'tumult/lib/perlin/perlinN' {
    declare module.exports: any;
}

declare module 'tumult/lib/simplex/simplex1' {
    declare module.exports: any;
}

declare module 'tumult/lib/simplex/simplex2' {
    declare module.exports: any;
}

declare module 'tumult/lib/util/1d' {
    declare module.exports: any;
}

declare module 'tumult/lib/util/2d' {
    declare module.exports: any;
}

declare module 'tumult/lib/util/3d' {
    declare module.exports: any;
}

declare module 'tumult/lib/util/4d' {
    declare module.exports: any;
}

declare module 'tumult/lib/util/math' {
    declare module.exports: any;
}

declare module 'tumult/lib/util/nd' {
    declare module.exports: any;
}

declare module 'tumult/lib/util/noise' {
    declare module.exports: any;
}

declare module 'tumult/pages/demo.c8d0cba3' {
    declare module.exports: any;
}

// Filename aliases
declare module 'tumult/dist/tumult.min.js' {
    declare module.exports: $Exports<'tumult/dist/tumult.min'>;
}
declare module 'tumult/index' {
    declare module.exports: $Exports<'tumult'>;
}
declare module 'tumult/index.js' {
    declare module.exports: $Exports<'tumult'>;
}
declare module 'tumult/lib/index' {
    declare module.exports: $Exports<'tumult/lib'>;
}
declare module 'tumult/lib/index.js' {
    declare module.exports: $Exports<'tumult/lib'>;
}
declare module 'tumult/lib/perlin/perlin1.js' {
    declare module.exports: $Exports<'tumult/lib/perlin/perlin1'>;
}
declare module 'tumult/lib/perlin/perlin2.js' {
    declare module.exports: $Exports<'tumult/lib/perlin/perlin2'>;
}
declare module 'tumult/lib/perlin/perlin3.js' {
    declare module.exports: $Exports<'tumult/lib/perlin/perlin3'>;
}
declare module 'tumult/lib/perlin/perlin4.js' {
    declare module.exports: $Exports<'tumult/lib/perlin/perlin4'>;
}
declare module 'tumult/lib/perlin/perlinN.js' {
    declare module.exports: $Exports<'tumult/lib/perlin/perlinN'>;
}
declare module 'tumult/lib/simplex/simplex1.js' {
    declare module.exports: $Exports<'tumult/lib/simplex/simplex1'>;
}
declare module 'tumult/lib/simplex/simplex2.js' {
    declare module.exports: $Exports<'tumult/lib/simplex/simplex2'>;
}
declare module 'tumult/lib/util/1d.js' {
    declare module.exports: $Exports<'tumult/lib/util/1d'>;
}
declare module 'tumult/lib/util/2d.js' {
    declare module.exports: $Exports<'tumult/lib/util/2d'>;
}
declare module 'tumult/lib/util/3d.js' {
    declare module.exports: $Exports<'tumult/lib/util/3d'>;
}
declare module 'tumult/lib/util/4d.js' {
    declare module.exports: $Exports<'tumult/lib/util/4d'>;
}
declare module 'tumult/lib/util/math.js' {
    declare module.exports: $Exports<'tumult/lib/util/math'>;
}
declare module 'tumult/lib/util/nd.js' {
    declare module.exports: $Exports<'tumult/lib/util/nd'>;
}
declare module 'tumult/lib/util/noise.js' {
    declare module.exports: $Exports<'tumult/lib/util/noise'>;
}
declare module 'tumult/pages/demo.c8d0cba3.js' {
    declare module.exports: $Exports<'tumult/pages/demo.c8d0cba3'>;
}
