// @flow

export const TOKEN_INVALID_PRIVATE_KEY: 'TOKEN_INVALID_PRIVATE_KEY'
    = `TOKEN_INVALID_PRIVATE_KEY`;
export const TOKEN_UNPARSABLE: 'TOKEN_UNPARSABLE' = `TOKEN_UNPARSABLE`;
export const TOKEN_WITHOUT_USERNAME: 'TOKEN_WITHOUT_USERNAME'
    = `TOKEN_WITHOUT_USERNAME`;

export type TokenType =
    | typeof TOKEN_INVALID_PRIVATE_KEY
    | typeof TOKEN_UNPARSABLE
    | typeof TOKEN_WITHOUT_USERNAME;
