// flow-typed signature: eedd411a21b8dd13960511303b29ccfc
// flow-typed version: <<STUB>>/simple-websocket_v8.1.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-websocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-websocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-websocket/server' {
  declare module.exports: any;
}

declare module 'simple-websocket/simplewebsocket.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-websocket/index' {
  declare module.exports: $Exports<'simple-websocket'>;
}
declare module 'simple-websocket/index.js' {
  declare module.exports: $Exports<'simple-websocket'>;
}
declare module 'simple-websocket/server.js' {
  declare module.exports: $Exports<'simple-websocket/server'>;
}
declare module 'simple-websocket/simplewebsocket.min.js' {
  declare module.exports: $Exports<'simple-websocket/simplewebsocket.min'>;
}
