// flow-typed signature: 547152dbc3c6d9d6cce85068899c32bf
// flow-typed version: <<STUB>>/@icon/icofont_v1.0.1-alpha.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@icon/icofont'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@icon/icofont' {
  declare module.exports: any;
}
